[application]

tailwind_input = "crates/web/tailwind.css"
tailwind_output = "crates/web/assets/tailwind.css"

[web.watcher]
watch_path = ["crates/core/src", "crates/web/src", "crates/web/assets"]

[web.app]

# HTML title tag content
title = "The Just Dance Archives"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
